### ISSUE TITLE
SDK version 1.0.41 client initialization fails

### ISSUE THREAD

**Issue by mohabusama** [spotinst/spotinst-sdk-python#28] opened 2018-11-05 13:35 UTC
Verison 1.0.41 client initialization parses process arguments which leads to failure due to unrecognized args.
Fails in calling `self.get_args()`
https://github.com/spotinst/spotinst-sdk-python/blob/master/spotinst_sdk/__init__.py#L82
https://github.com/spotinst/spotinst-sdk-python/blob/master/spotinst_sdk/__init__.py#L3503

**Comment by anuragsharma-123** [comment] 2023-01-14 19:54
The issue is obsolete with latest releases. Closing it.

**Closed as completed by anuragsharma-123** 2023-01-14 19:54 UTC
